# Generated by Django 3.0.8 on 2021-06-02 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20200730_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('Firm', models.CharField(max_length=255, verbose_name='Фирма производитель')),
                ('Country', models.CharField(max_length=255, verbose_name='Страна')),
                ('Weight', models.CharField(max_length=255, verbose_name='Вес')),
                ('Color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('shelf_life', models.CharField(max_length=255, verbose_name='Срок годности')),
                ('Article', models.CharField(max_length=20, verbose_name='Артикул товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('Firm', models.CharField(max_length=255, verbose_name='Фирма производитель')),
                ('Country', models.CharField(max_length=255, verbose_name='Страна')),
                ('Weight', models.CharField(max_length=255, verbose_name='Вес')),
                ('shelf_life', models.CharField(max_length=255, verbose_name='Срок годности')),
                ('Article', models.CharField(max_length=20, verbose_name='Артикул товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Oils',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('Firm', models.CharField(max_length=255, verbose_name='Фирма производитель')),
                ('Country', models.CharField(max_length=255, verbose_name='Страна')),
                ('Volume', models.CharField(max_length=255, verbose_name='Объем')),
                ('Color', models.CharField(max_length=255, verbose_name='Цвет')),
                ('shelf_life', models.CharField(max_length=255, verbose_name='Срок годности')),
                ('Article', models.CharField(max_length=20, verbose_name='Артикул товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('Firm', models.CharField(max_length=255, verbose_name='Фирма производитель')),
                ('Country', models.CharField(max_length=255, verbose_name='Страна')),
                ('Weight', models.CharField(max_length=255, verbose_name='Вес')),
                ('shelf_life', models.CharField(max_length=255, verbose_name='Срок годности')),
                ('Article', models.CharField(max_length=20, verbose_name='Артикул товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='category',
        ),
        migrations.DeleteModel(
            name='Notebook',
        ),
        migrations.DeleteModel(
            name='Smartphone',
        ),
    ]
